name: Pre-Commit

on:
  pull_request:
    branches:
      - main

env:
  TERRAFORM_VERSION: '1.10.5'
  TFLINT_VERSION: v0.57.0

jobs:
  preCommit:
    name: Terraform pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-commit Terraform ${{ env.TERRAFORM_VERSION }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.11.1
        with:
          terraform-version: ${{ env.TERRAFORM_VERSION }}
          tflint-version: ${{ env.TFLINT_VERSION }}
